name: flutter_jap_icons
description: Just Another package of icons. This package contains medical, maps and geoglyphs icons. Enjoy it.
version: 0.1.0
homepage: https://github.com/ajomuch92/flutter-jap-icons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family:  GeoglyphsIcons
      fonts:
        - asset: fonts/GeoglyphsIcons.ttf
    - family:  MapIcons
      fonts:
        - asset: fonts/MapIcons.ttf
    - family:  MedicalIcons
      fonts:
        - asset: fonts/MedicalIcons.ttf
